# Generated by Django 5.1.7 on 2025-05-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('For Interview', 'For Interview'), ('For Exam', 'For Exam'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Applied', max_length=20)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job.company')),
            ],
        ),
    ]
