# Generated by Django 5.1.7 on 2025-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='notes',
        ),
        migrations.AddField(
            model_name='apply',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='full_current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='job_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
