# Generated by Django 5.1.7 on 2025-05-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcategory', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Workfrom-Home', 'Workfrom-Home')], default='Full-Time', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salarystatus', models.CharField(max_length=255)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='location_images/')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.employeeposition')),
            ],
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='job.position'),
        ),
    ]
