# Generated by Django 5.1.7 on 2025-04-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcategory', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Workfrom-Home', 'Workfrom-Home')], default='Full-Time', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salarystatus', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.position')),
            ],
        ),
    ]
